<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\CelesteDesktop.AssetWorker.Meta\CelesteDesktop.AssetWorker.Meta.csproj" />
    <ProjectReference Include="..\..\src\CelesteDesktop.AssetWorker.Data\CelesteDesktop.AssetWorker.Data.csproj" />
    <ProjectReference Include="..\..\src\CelesteDesktop.AssetWorker.SpriteXml\CelesteDesktop.AssetWorker.SpriteXml.csproj" />
    <ProjectReference Include="..\..\src\CelesteDesktop.AssetWorker.Catalog\CelesteDesktop.AssetWorker.Catalog.csproj" />
    <ProjectReference Include="..\..\src\CelesteDesktop.Simulation.Core\CelesteDesktop.Simulation.Core.csproj" />
    <ProjectReference Include="..\..\src\CelesteDesktop.Player\CelesteDesktop.Player.csproj" />
    <ProjectReference Include="..\..\src\CelesteDesktop.Rendering\CelesteDesktop.Rendering.csproj" />
    <ProjectReference Include="..\..\src\CelesteDesktop.Desktop\CelesteDesktop.Desktop.csproj" />
    <ProjectReference Include="..\..\src\CelesteDesktop.Animation\CelesteDesktop.Animation.csproj" />
    <ProjectReference Include="..\..\src\CelesteDesktop.Entity.Theo\CelesteDesktop.Entity.Theo.csproj" />
    <ProjectReference Include="..\..\src\CelesteDesktop.Entity.Glider\CelesteDesktop.Entity.Glider.csproj" />
    <ProjectReference Include="..\..\src\CelesteDesktop.Entity.Spring\CelesteDesktop.Entity.Spring.csproj" />
    <ProjectReference Include="..\..\src\CelesteDesktop.Entity.Refill\CelesteDesktop.Entity.Refill.csproj" />
  </ItemGroup>
</Project>
