<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\CelesteDesktop.Contracts\CelesteDesktop.Contracts.csproj" />
    <ProjectReference Include="..\..\src\CelesteDesktop.Rendering\CelesteDesktop.Rendering.csproj" />
    <ProjectReference Include="..\..\src\CelesteDesktop.Rendering.Windows\CelesteDesktop.Rendering.Windows.csproj" />
  </ItemGroup>
</Project>
