<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\CelesteDesktop.Contracts\CelesteDesktop.Contracts.csproj" />
    <ProjectReference Include="..\..\src\CelesteDesktop.Install\CelesteDesktop.Install.csproj" />
  </ItemGroup>
</Project>
