namespace CelesteDesktop.Player;

public sealed record PlayerTraversalTuning(
    decimal DashSpeed,
    decimal EndDashSpeed,
    decimal EndDashUpMultiplier,
    int DashTicks,
    int DashCooldownTicks,
    int DashRefillCooldownTicks,
    int DashAttackTicks,
    int WallJumpCheckDistance,
    decimal WallJumpHorizontalSpeed,
    decimal WallJumpVerticalSpeed,
    decimal WallSlideStartMax,
    int WallSlideTicks,
    decimal ClimbMaxStamina,
    decimal ClimbTiredThreshold,
    decimal ClimbUpCostPerSecond,
    decimal ClimbStillCostPerSecond,
    decimal ClimbJumpCost,
    int ClimbCheckDistance,
    int ClimbNoMoveTicks,
    decimal ClimbUpSpeed,
    decimal ClimbDownSpeed,
    decimal ClimbSlipSpeed,
    decimal ClimbAcceleration,
    decimal ClimbGrabYMultiplier,
    decimal ClimbHopX,
    decimal ClimbHopY)
{
    public static PlayerTraversalTuning ReferencePartial { get; } = new(
        DashSpeed: 240m,
        EndDashSpeed: 160m,
        EndDashUpMultiplier: 0.75m,
        DashTicks: 9,
        DashCooldownTicks: 12,
        DashRefillCooldownTicks: 6,
        DashAttackTicks: 18,
        WallJumpCheckDistance: 3,
        WallJumpHorizontalSpeed: 130m,
        WallJumpVerticalSpeed: -105m,
        WallSlideStartMax: 20m,
        WallSlideTicks: 72,
        ClimbMaxStamina: 110m,
        ClimbTiredThreshold: 20m,
        ClimbUpCostPerSecond: 100m / 2.2m,
        ClimbStillCostPerSecond: 10m,
        ClimbJumpCost: 27.5m,
        ClimbCheckDistance: 2,
        ClimbNoMoveTicks: 6,
        ClimbUpSpeed: -45m,
        ClimbDownSpeed: 80m,
        ClimbSlipSpeed: 30m,
        ClimbAcceleration: 900m,
        ClimbGrabYMultiplier: 0.2m,
        ClimbHopX: 100m,
        ClimbHopY: -120m);
}
